
const SERVER_URL = "http://127.0.0.1:8000";
let selectedImageFile = null, loadedImage = null, cropRect = null, dragStart = null;
let extractedGraphData = [], extractedPoints = [], csvData = [], mixCandidates = [], chartInstance = null, voices = [];
const canvas = document.getElementById("imageCanvas"), ctx = canvas.getContext("2d"), canvasWrap = document.getElementById("canvasWrap");
const chartTypeSelect = document.getElementById("chartTypeSelect"), candleColorSelect = document.getElementById("candleColorSelect"), candleGuide = document.getElementById("candleGuide");
window.speechSynthesis.onvoiceschanged = () => { voices = window.speechSynthesis.getVoices(); };
document.getElementById("contrastToggle").addEventListener("change", e => document.body.classList.toggle("high-contrast", e.target.checked));
document.getElementById("freqSlider").addEventListener("input", e => document.getElementById("freqVal").innerText = e.target.value);
document.getElementById("waveSelect").addEventListener("change", () => { if (extractedGraphData.length > 0) prepareGraphAudio(); });
function setStatus(text) { document.getElementById("imageStatus").innerText = text; }
function updateChartTypeUI() { const type = chartTypeSelect.value; const isCandle = type === "candlestick"; candleColorSelect.disabled = !isCandle; candleGuide.hidden = !isCandle; }
chartTypeSelect.addEventListener("change", updateChartTypeUI); updateChartTypeUI();
document.getElementById("imageInput").addEventListener("change", e => { const file = e.target.files[0]; if (!file) return; selectedImageFile = file; const image = new Image(); image.onload = () => { loadedImage = image; cropRect = null; extractedPoints = []; extractedGraphData = []; fitCanvasToImage(image); canvasWrap.hidden = false; renderDebugImage(null); drawImageCanvas(); document.getElementById("analyzeImageBtn").disabled = false; setStatus("이미지가 업로드되었습니다. 결과가 이상하면 가격 차트 영역만 드래그하여 다시 분석하세요."); }; image.src = URL.createObjectURL(file); });
function fitCanvasToImage(image) { const maxWidth = Math.min(900, document.querySelector(".panel").clientWidth - 48), scale = Math.min(1, maxWidth / image.width); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.dataset.scale = scale; }
function drawImageCanvas() { if (!loadedImage) return; ctx.clearRect(0,0,canvas.width,canvas.height); ctx.drawImage(loadedImage,0,0,canvas.width,canvas.height); if (extractedPoints.length > 1) { const scale = Number(canvas.dataset.scale || 1); ctx.save(); ctx.lineWidth = 3; ctx.strokeStyle = "#d92828"; ctx.beginPath(); extractedPoints.forEach((p,i)=>{ const x=p.pixel_x*scale, y=p.pixel_y*scale; i===0 ? ctx.moveTo(x,y) : ctx.lineTo(x,y); }); ctx.stroke(); ctx.restore(); } if (cropRect) { ctx.save(); ctx.strokeStyle="#005fcc"; ctx.lineWidth=2; ctx.setLineDash([8,5]); ctx.strokeRect(cropRect.x,cropRect.y,cropRect.width,cropRect.height); ctx.fillStyle="rgba(0,95,204,.08)"; ctx.fillRect(cropRect.x,cropRect.y,cropRect.width,cropRect.height); ctx.restore(); } }
function canvasPosition(e) { const r = canvas.getBoundingClientRect(); return {x:e.clientX-r.left,y:e.clientY-r.top}; }
canvas.addEventListener("mousedown", e => { if (loadedImage) dragStart = canvasPosition(e); });
canvas.addEventListener("mousemove", e => { if (!dragStart) return; const p = canvasPosition(e); cropRect = normalizeRect(dragStart.x, dragStart.y, p.x - dragStart.x, p.y - dragStart.y); drawImageCanvas(); });
canvas.addEventListener("mouseup", () => dragStart = null); canvas.addEventListener("mouseleave", () => dragStart = null);
document.getElementById("resetSelectionBtn").addEventListener("click", () => { cropRect = null; extractedPoints = []; drawImageCanvas(); setStatus("그래프 영역 선택을 초기화했습니다. 전체 이미지를 분석합니다."); });
function normalizeRect(x,y,w,h){ const l=Math.max(0,Math.min(x,x+w)), t=Math.max(0,Math.min(y,y+h)), r=Math.min(canvas.width,Math.max(x,x+w)), b=Math.min(canvas.height,Math.max(y,y+h)); return {x:l,y:t,width:r-l,height:b-t}; }
document.getElementById("analyzeImageBtn").addEventListener("click", analyzeImage); document.getElementById("playGraphAudioBtn").addEventListener("click", () => playAudio("graphAudio")); document.getElementById("readDescriptionBtn").addEventListener("click", readGraphDescription);
async function analyzeImage(){ if(!selectedImageFile)return; setStatus("그래프를 분석하는 중입니다."); document.getElementById("analyzeImageBtn").disabled=true; const formData=new FormData(); formData.append("image",selectedImageFile); formData.append("chart_type",chartTypeSelect.value); formData.append("color_scheme",candleColorSelect.value); const scale=Number(canvas.dataset.scale||1); if(cropRect&&cropRect.width>10&&cropRect.height>10){ formData.append("crop_x",Math.round(cropRect.x/scale)); formData.append("crop_y",Math.round(cropRect.y/scale)); formData.append("crop_width",Math.round(cropRect.width/scale)); formData.append("crop_height",Math.round(cropRect.height/scale)); } try{ const res=await fetch(`${SERVER_URL}/analyze-graph-image`,{method:"POST",body:formData}), payload=await res.json(); if(!res.ok) throw new Error(payload.detail||"이미지 분석에 실패했습니다."); extractedGraphData=payload.data||[]; extractedPoints=payload.points||[]; renderDescription(payload.analysis,payload.confidence); renderDebugImage(payload.debug_image); drawImageCanvas(); await prepareGraphAudio(); document.getElementById("playGraphAudioBtn").disabled=false; document.getElementById("readDescriptionBtn").disabled=false; setStatus(statusText(payload)); } catch(error){ renderDebugImage(null); setStatus(`${error.message} 결과가 불안정하면 가격 차트 영역만 다시 드래그하거나 캔들 색상 설정을 변경해 주세요.`); } finally{ document.getElementById("analyzeImageBtn").disabled=false; } }
function statusText(payload){ if(payload.chart_type==="candlestick"){ const conf=payload.confidence?Math.round(payload.confidence.score*100):"?"; return `분석 완료. 예상 캔들 ${payload.expected_candles||"?"}개, 선택 ${payload.selected_candles||0}개, fallback ${payload.fallback_recovered||0}개, 누락 ${payload.missing_candles||0}개, 신뢰도 ${conf}%입니다.`; } return "분석이 완료되었습니다. 빨간 선은 시스템이 추출한 그래프 흐름입니다."; }
function renderDescription(analysis,confidence){ const summary=document.getElementById("graphSummary"), list=document.getElementById("descriptionList"); summary.innerText=analysis?analysis.summary:"분석 결과가 없습니다."; list.innerHTML=""; if(confidence){ const li=document.createElement("li"); li.innerText=`분석 신뢰도: ${Math.round(confidence.score*100)}%, 단계: ${confidence.level}`; list.appendChild(li); } (analysis?.descriptions||[]).forEach(text=>{ const li=document.createElement("li"); li.innerText=text; list.appendChild(li); }); }
function renderDebugImage(src){ const wrap=document.getElementById("debugWrap"), img=document.getElementById("debugImage"); if(!wrap||!img)return; if(src){ img.src=src; wrap.hidden=false; } else { img.removeAttribute("src"); wrap.hidden=true; } }
async function prepareGraphAudio(){ if(extractedGraphData.length===0)return; const blob=await requestAudio(extractedGraphData,document.getElementById("waveSelect").value); document.getElementById("graphAudio").src=URL.createObjectURL(blob); }
async function requestAudio(data,waveform){ const payload={data,max_freq:Number(document.getElementById("freqSlider").value),waveform}; const res=await fetch(`${SERVER_URL}/sonify-data`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); if(!res.ok) throw new Error("음향 생성에 실패했습니다."); return await res.blob(); }
function readGraphDescription(){ stopAllAudio(); const msg=new SpeechSynthesisUtterance(document.getElementById("graphSummary").innerText); msg.lang="ko-KR"; msg.rate=1.05; const ko=voices.find(v=>v.lang.includes("ko")); if(ko)msg.voice=ko; window.speechSynthesis.speak(msg); }
function stopAllAudio(){ window.speechSynthesis.cancel(); document.querySelectorAll("audio").forEach(a=>{a.pause();a.currentTime=0;}); }
function playAudio(id){ stopAllAudio(); const a=document.getElementById(id); if(a&&a.src)a.play(); }
document.getElementById("csvInput").addEventListener("change", e=>{ const file=e.target.files[0]; if(!file)return; Papa.parse(file,{header:true,dynamicTyping:true,skipEmptyLines:true,complete:r=>processCSV(r.data)}); });
function processCSV(rows){ if(!rows.length)return alert("CSV 데이터가 없습니다."); const columns=Object.keys(rows[0]), keys=["time","date","index","year","month","day","시간","날짜","연도"]; let labels=rows.map((_,i)=>i+1), dataColumns=[...columns]; if(keys.some(k=>columns[0].toLowerCase().includes(k))){ labels=rows.map(row=>row[columns[0]]); dataColumns=columns.slice(1); } csvData=dataColumns.map(column=>{ const raw=rows.map(row=>Number(row[column])).filter(Number.isFinite); if(!raw.length)return null; const min=Math.min(...raw), max=Math.max(...raw), scaled=raw.map(v=>max!==min?(v-min)/(max-min):.5); return {name:column,raw,scaled,min,max}; }).filter(Boolean); drawCsvChart(labels,csvData); renderCsvResults(); }
function drawCsvChart(labels,datasets){ const el=document.getElementById("lineChart"); if(chartInstance)chartInstance.destroy(); chartInstance=new Chart(el,{type:"line",data:{labels,datasets:datasets.map((d,i)=>({label:d.name,data:d.scaled,borderColor:`hsl(${i*97%360},72%,42%)`,borderWidth:2,pointRadius:2,tension:.15}))},options:{responsive:true,scales:{y:{min:0,max:1,ticks:{display:false}}}}}); }
function renderCsvResults(){ const container=document.getElementById("csvResults"); container.innerHTML=""; document.getElementById("mixPanel").hidden=csvData.length===0; csvData.forEach((d,i)=>{ const card=document.createElement("article"); card.className="data-card"; card.innerHTML=`<div><h3>${d.name}</h3><p>원본 최소 ${d.min.toFixed(2)}, 원본 최대 ${d.max.toFixed(2)}</p></div><div class="card-actions"><label><input type="checkbox" id="mixCheck_${i}"> 믹싱 포함</label><button class="btn-secondary" type="button" id="csvPlay_${i}">재생</button><audio id="csvAudio_${i}" controls></audio></div>`; container.appendChild(card); document.getElementById(`csvPlay_${i}`).addEventListener("click",async()=>{ const blob=await requestAudio(d.scaled,"sine"), audio=document.getElementById(`csvAudio_${i}`); audio.src=URL.createObjectURL(blob); playAudio(`csvAudio_${i}`); }); document.getElementById(`mixCheck_${i}`).addEventListener("change",updateMixCandidates); }); updateMixCandidates(); }
function updateMixCandidates(){ mixCandidates=csvData.filter((_,i)=>{ const c=document.getElementById(`mixCheck_${i}`); return c&&c.checked; }); document.getElementById("mixListText").innerText=mixCandidates.length?`선택된 데이터: ${mixCandidates.map(i=>i.name).join(", ")}`:"선택된 데이터가 없습니다."; }
document.getElementById("mixBtn").addEventListener("click",async()=>{ if(!mixCandidates.length)return alert("믹싱할 데이터를 선택해 주세요."); const payload={data_list:mixCandidates.map(i=>i.scaled),max_freq:Number(document.getElementById("freqSlider").value),waveform_list:mixCandidates.map(()=>"sine")}; const res=await fetch(`${SERVER_URL}/mix-data`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}), blob=await res.blob(), audio=document.getElementById("mixAudio"); audio.src=URL.createObjectURL(blob); playAudio("mixAudio"); });
document.addEventListener("keydown",e=>{ if(e.ctrlKey||e.metaKey||e.altKey)return; if(e.key==="Escape")stopAllAudio(); if(e.key.toLowerCase()==="i")document.getElementById("imageInput").click(); if(e.key.toLowerCase()==="a"&&!document.getElementById("analyzeImageBtn").disabled)analyzeImage(); if(e.key===" "&&!document.getElementById("playGraphAudioBtn").disabled){ e.preventDefault(); playAudio("graphAudio"); } });
